version: "3.9"

services:
  wordpress:
    build: .
    container_name: wordpress
    restart: always
    depends_on:
      - mysql
    stdin_open: true
    tty: true
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: houssem
      WORDPRESS_DB_PASSWORD: Hafidha_18
      WORDPRESS_DB_NAME: trademarketnews
      WORDPRESS_TABLE_PREFIX: 365_m_
      WORDPRESS_CONFIG_EXTRA: |
        define('DISABLE_WP_CRON', true);
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: trademarketnews
      MYSQL_USER: houssem
      MYSQL_PASSWORD: Hafidha_18
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql:/var/lib/mysql

  nginx:
    image: lscr.io/linuxserver/swag
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx:/config
      - ./docker/nginx/nginx.conf:/config/nginx/site-confs/default
      - ./docker/nginx/ssl.conf:/config/nginx/ssl.conf
    container_name: nginx
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=trademarketnews.com
      - SUBDOMAINS=www,
      - VALIDATION=http
      - STAGING=false #optional

volumes:
    wordpress:
    mysql:
    nginx: